### ISSUE TITLE
SMA Flow crashed

### ISSUE THREAD

**Issue by MaAr389** [rlindner/node-red-contrib-sma-webconnect#42]
Hi there, 

my flow is crashing. I get following error message.
I'm not sure where the error message comes from. Anyone have any ideas?

`16 Feb 07:32:18 - [info] [sma-webconnect:a2ca0883145b3548] http://172.16.200.6/dyn/logout.json?sid=null
16 Feb 07:32:18 - [info] Stopped flows
16 Feb 07:32:18 - [info] Updated flows
16 Feb 07:32:18 - [info] Starting flows
16 Feb 07:32:18 - [info] Started flows
16 Feb 07:32:18 - [info] [mqtt-broker:Server-Mqtt] Connection failed to broker: mqtt://localhost:1883
16 Feb 07:32:19 - [info] [sma-webconnect:4c2cfba6ab1c6d72] session created: 172.16.200.6 : kFHQDEQkDwMkQGgz
16 Feb 07:32:20 - [red] Uncaught Exception:
16 Feb 07:32:20 - [error] TypeError: value[config.id] is not iterable
    at parseResult (C:\Users\Martin\.node-red\node_modules\node-red-contrib-sma-webconnect\functions.js:22:36)
    at Request.<anonymous> (C:\Users\Martin\.node-red\node_modules\node-red-contrib-sma-webconnect\sma-webconnect.js:105:30)
    at Request._callback (C:\Users\Martin\.node-red\node_modules\lodash\lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (C:\Users\Martin\.node-red\node_modules\requestretry\index.js:151:19)
    at Request.<anonymous> (C:\Users\Martin\.node-red\node_modules\requestretry\index.js:192:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by HoLo85** [comment]
Looks like a wrong config `TypeError: value[config.id]` . Did you change something in the config of the node?
